# Generated by Django 4.1 on 2022-08-22 03:22

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="Property title"),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        populate_from="title",
                        unique=True,
                    ),
                ),
                (
                    "ref_code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Property Reference Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Default description...", verbose_name="Description"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Country"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Postal code"),
                ),
                (
                    "street_address",
                    models.CharField(max_length=150, verbose_name="Street address"),
                ),
                (
                    "property_number",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Property number",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Price"
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.05,
                        help_text="Tax upon property price",
                        max_digits=6,
                        verbose_name="Tax",
                    ),
                ),
                (
                    "plot_area",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Plot area (m^2)",
                    ),
                ),
                (
                    "number_of_floors",
                    models.IntegerField(default=0, verbose_name="Number of floors"),
                ),
                (
                    "number_of_bedrooms",
                    models.IntegerField(default=0, verbose_name="Number of bedrooms"),
                ),
                (
                    "number_of_bathrooms",
                    models.IntegerField(default=0, verbose_name="Number of bathrooms"),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("House", "House"),
                            ("Apartment", "Apartment"),
                            ("Office", "Office"),
                            ("Warehouse", "Warehouse"),
                            ("Commercial", "Commercial"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                        verbose_name="Property type",
                    ),
                ),
                (
                    "advert_type",
                    models.CharField(
                        choices=[
                            ("For Sale", "For Sale"),
                            ("For Rent", "For Rent"),
                            ("For Auction", "For Auction"),
                        ],
                        default="For Sale",
                        max_length=50,
                        verbose_name="Advert type",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        default="/sample_property_cover_image.jpg",
                        null=True,
                        upload_to="",
                        verbose_name="Cover image",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True,
                        default="/sample_property_image1.jpg",
                        null=True,
                        upload_to="",
                        verbose_name="Image 1",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        default="/sample_property_image2.jpg",
                        null=True,
                        upload_to="",
                        verbose_name="Image 2",
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        default="/sample_property_image3.jpg",
                        null=True,
                        upload_to="",
                        verbose_name="Image 3",
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True,
                        default="/sample_property_image4.jpg",
                        null=True,
                        upload_to="",
                        verbose_name="Image 4",
                    ),
                ),
                (
                    "published_status",
                    models.BooleanField(default=False, verbose_name="Published status"),
                ),
                (
                    "views",
                    models.IntegerField(default=0, verbose_name="Number of views"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="agent_or_buyer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent, seller, or Buyer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.CreateModel(
            name="PropertyView",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "viewer_ip",
                    models.CharField(max_length=250, verbose_name="Viewer IP address"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_views",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Total views on Property",
                "verbose_name_plural": "Total Property Views",
            },
        ),
    ]
